apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-deployment.yaml
  - products-deployment.yaml
  - customers-deployment.yaml
  - orders-deployment.yaml
  - databases.yaml
  - microservices-hpa.yaml
